steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', '--depth', '1', 'https://github.com/SalgadoFab/task-manager.git']
- name: 'node:14'
  entrypoint: 'npm'
  args: ['install']
  dir: 'task-manager'
- name: 'node:14'
  entrypoint: 'npm'
  args: ['run', 'build']
  dir: 'task-manager'
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rsync', '-r', '-c', '-d', './task-manager/dist', 'gs://task-manager-bucket']
timeout: 1800s

